IGNF/cartes.gouv.fr-entree-carto

- src/views/Main.vue
PR pour répondre à la demande https://github.com/IGNF/cartes.gouv.fr/issues/463
Pas de bêta dans le header
> feat(header): ajout mention beta derrière le titre

- src/components.d.ts
- src/components/menu/MenuLateralWrapper.vue
- src/components/modals/ModalConsent.vue
- src/components/modals/ModalTheme.vue
- src/composables/footerParams.js
- src/main.ts
- src/plugins/Eulerian.js
- src/router/index.ts
- src/views/Main.vue
- vite.config.ts
Modale des **cookies**
Collecte **Eulerian**
> Gestion des cookies et Eulerian

- src/components/menu/MenuLateralWrapper.vue
Le menu de droite ne s'affiche pas correctement quand le thème(dark/light) est changé par l'utilisateur
Le menu des widgets s'adapte correctement au thème (sombre/light) sélectionné.
> 🚑 switch theme color menu

- src/composables/controls.js
- src/stores/mapStore.js
Quand on visite le site pour la première fois (localStorage.clear() pour simuler), aucun widget n'est ajouté à la carte.
Une liste de controls "actifs" par défaut est ajouté à la carte quand on visite le site pour la première fois.
> fix(localStorage): liste de controls ajoutés à la première visite

- src/views/Main.vue
fix #288
Mode mobile menu hamburger : 
Mode mobile, menu hamburger : 
Fix #288
> fix(header): ajout de la navigation dans le menu hamburger mobile

- src/components/menu/MenuControl.vue
Réponse à ce commentaire
https://github.com/IGNF/cartes.gouv.fr-entree-carto/issues/295#issuecomment-2297106915
> 🚑 mes outils apres ajouter des outils

- src/components/carte/Controls.vue
- src/components/carte/control/Isocurve.vue
- src/composables/controls.js
- src/main.ts
- src/plugins/Eulerian.js
On est sur un test de collecte customisée sur le composant l'isochrone.
**Ça ne semble pas fonctionner !? Et, je ne sais pas pourquoi...**
cf. #178
> Collecte Eulerian des interaction avec les widgets

- src/views/Main.vue
https://github.com/IGNF/cartes.gouv.fr-entree-carto/issues/289
Juste la partie "header". La partie footer est faite ici : https://github.com/IGNF/cartes.gouv.fr-entree-carto/pull/304
https://github.com/IGNF/cartes.gouv.fr-entree-carto/issues/289
> feat(mobile): mini header

- src/assets/arrow-down.svg
- src/views/Main.vue
https://github.com/IGNF/cartes.gouv.fr-entree-carto/issues/289
Juste la partie "footer". La partie "header" est faite ici https://github.com/IGNF/cartes.gouv.fr-entree-carto/pull/305
https://github.com/IGNF/cartes.gouv.fr-entree-carto/issues/289
> feat(mobile): small footer

- DRAFT_CHANGELOG.md
- src/components.d.ts
- src/components/carte/Controls.vue
- src/components/carte/Map.vue
- src/components/carte/control/MousePosition.vue
- src/composables/controls.js
- src/composables/layer.js
- Ajout du widget **mousePosition** à l'interface
- Ajout du système de projection  UTM pour les territoires
> 🌟 ajout de l'extension mouse position

- src/stores/mapStore.js
Quand aucune couche ajoutée (0 couches dans LS), la synchro entre le catalogue et le layerswitcher se fait bien. (côté mapstore, l'objet layers retourne bien un tableau vide)
> 🚑 fix https://github.com/IGNF/cartes.gouv.fr-entree-carto/issues/317

- public/data/edito.json
- src/components/carte/control/Share.vue
> fix(share:mail): pas de destinataire par défaut + saut de ligne dans body du mail

- src/components/carte/Map.vue
fixes https://github.com/IGNF/cartes.gouv.fr-entree-carto/issues/323
Pas de perte de focus des balises SELECT au hover sur la map
> fix(focus): edge focus select tags

- src/components/carte/Controls.vue
- src/composables/controls.js
- search engine et layerswitcher n'apparaissent plus dans le menu des widgets et sont activés par défaut
-
-
> widget par défaut : searchengine et layswitcher

- src/components/carte/control/Share.vue
- src/components/menu/MenuLateralNavButton.vue
fixes https://github.com/IGNF/cartes.gouv.fr-entree-carto/issues/351
> style(button): Passer les boutons partage et menu en secondaire

- src/components/carte/control/Share.vue
- src/components/menu/LeftMenuTool.vue
- src/components/menu/MenuLateralNavButton.vue
- src/components/menu/MenuLateralWrapper.vue
- src/components/menu/RightMenuTool.vue
fixes https://github.com/IGNF/cartes.gouv.fr-entree-carto/issues/358
> feat(tooltip): tooltip sur les boutons spécifiques entrée carto

- src/components/carte/control/Share.vue
- src/components/menu/MenuLateralNavButton.vue
- src/components/menu/MenuLateralWrapper.vue
fixes https://github.com/IGNF/cartes.gouv.fr-entree-carto/issues/374
> fix(tooltips): double tooltips + mauvais sens pour catalogue d'outils

- src/components/carte/Controls.vue
- src/composables/controls.js
- src/stores/appStore.js
Breaking Change : localStorage VERSION
@IGNFhc Possibilité de cacher les controles obligatoires du menu au lieu de les griser ?
Vor si tu peux reprendre cette PR sur la tienne
Les widgets par défaut sont bien non selectionnables dans le menu
Nouvelle version du LocalStorage pour forcer la mise à jour de la liste côté client
> fix(widgets): liste des widgets par défaut mise à jour

- src/components/carte/Controls.vue
fixes https://github.com/IGNF/cartes.gouv.fr-entree-carto/issues/399
> fix: Affichage Panel plein écran avec scrolle sur footer

- index.html
`npm run dev` a bien fonctionné mais pas le `run build`. Mais pour des raisons indépendantes de cette PR. Il manque peut-être des instructions d'installation dans le readme.
Comme la page était déclarée en anglais, certains navigateurs proposaient la traduction systématiquement (typiquement firefox).
Avec la page déclarée en français, la déclaration correspond au contenu effectif et le navigateur ne propose plus de la traduire.
> fix: change la langue du html de base

- src/components/menu/MenuControl.vue
Le menu des widgets ne dépasse plus en bas
> 🚑 menu control size fix

- src/components/carte/Layer/Layer.vue
- src/composables/layer.js
fix #384
Les couches mapBox sont ajoutées avec le paramètre declutter à true depuis le catalogue de l'entrée carto. Cela vise à améliorer le rendu (cf https://github.com/IGNF/cartes.gouv.fr-entree-carto/issues/384#issuecomment-2569039529)
Attention, pour plan IGN, il faudrait une modification du style lui même et passer le paramètre allowOverlap à false.
QUESTION : côté entrée carto, à quoi sert la fonction **getLayerConf** dans 
> src/composables/layers.js
?
> feat(layer:tms): ajout de l'option declutter à true en option des TMS

- src/components/menu/MenuLateralWrapper.vue
fixes https://github.com/IGNF/cartes.gouv.fr-entree-carto/issues/453
> fix: menu btns visible over advanced search

- DRAFT_CHANGELOG.md
- src/components/carte/Controls.vue
- src/components/menu/MenuLateralNavButton.vue
- src/stores/mapStore.js
vérifier qu'un bouton "Ajouter des données" est présent dans le menu contextuel et que le panneau du catalogue s'ouvre
https://github.com/IGNF/cartes.gouv.fr-entree-carto/issues/160
> 🌟 catalogue ajouté au menu contextuel

- src/components/modals/ModalConsent.vue
- vite.config.ts
Suppression des warnings de la console au démarrage du serveur :
pour info
> Fix sur les warnings en console

- src/components/menu/catalogue/MenuCatalogue.vue
menu catalogue
Vérifier que la liste ne dépasse pas le menu
> 🚑 css height

- DRAFT_CHANGELOG.md
- src/components/carte/control/SearchEngine.vue
cf https://github.com/IGNF/geopf-extensions-openlayers/issues/321#issuecomment-2654040770 (ticket extension mais bug entrée carto)
> fix(advanced-search): qui dépasse notamment en mode cadastre

- src/components/carte/control/Drawing.vue
- src/components/carte/control/ElevationPath.vue
- src/components/carte/control/Isocurve.vue
- src/components/carte/control/Route.vue
- src/components/menu/bookmarks/MenuBookMarkNoData.vue
++ ajouts des boutons export pour les outils de calcul...
Recette: 
- modifier `IAM_DISABLE=1` dans le fichier .env.development
- `npm run dev`
- ouvrir les widgets Drawing, Elevation, Isocurve et Route
> Désactivation des boutons Enregistrer si l'authentification est désactivée

- DRAFT_CHANGELOG.md
- src/components/CartoAndTools.vue
- src/components/carte/control/PrintModal.vue
Avant cette PR la modal print ne s'ouvre plus.
Après ça refonctionne.
> 🚑 update des props composants Layers pas répercuté dans le code

- src/components/CartoAndTools.vue
- src/components/carte/control/LayerImport.vue
- src/features/share.js
- src/services/ServiceSetDocuments.js
- src/stores/mapStore.js
cf. issue #534 
Pour tester, 
* Ajouter une couche bidon dans le localStorage : ex. TEST(1;1;0)
* Ajouter une url de partage bidon : ex. kjfhzemrhmezjrhzemjhr.bin?format=
Une notification d'exception doit apparaître.
Le localStorage doit être nettoyé des couches bidons.
> [espace perso] Écarter les couches inconnues 

- src/components/CartoAndTools.vue
- src/views/Main.vue
https://github.com/IGNF/cartes.gouv.fr-entree-carto/issues/574
> 💄 on enlève le footer en mode mobile

- DRAFT_CHANGELOG.md
- src/stores/mapStore.js
6 chiffres après la virgule dans les coordonnées du centre du permalien (sous tache du #524)
> feat(share): reduction à 6 chiffres après la virgule des coords du permalien

- env/.env.demo
- env/.env.development
- env/.env.development-local
- env/.env.docker-dev-local
- env/.env.docker-local
- env/.env.production
- public/data/alerts.json
- src/components/modals/ModalInformation.vue
- src/stores/dataStore.js
- src/stores/mapStore.js
Branchement de la carto sur le système d'alertes de cartes.gouv.fr
EVOL
FIXME
> Si l'utilisateur décide de ne plus afficher les alertes
> comment reactiver l'affichage en cas de nouvelles alertes ?
> Gestion des alertes

- DRAFT_CHANGELOG.md
- src/components/menu/bookmarks/MenuBookMarkDataList.vue
- src/components/menu/bookmarks/MenuBookMarkEntry.vue
- src/composables/urlParams.js
- src/features/permalink.js
- src/features/translation.js
Dans le menu des favoris, on ajoute un bouton pour copier le permalien :
> Ajout fonctionnalité : Copie du permalien dans le menu des favoris

- CHANGELOG.md
- DRAFT_CHANGELOG.md
- src/components.d.ts
- src/components/menu/ControlListElement.vue
- src/components/menu/MenuControl.vue
- src/composables/controls.js
ticket https://github.com/IGNF/cartes.gouv.fr-entree-carto/issues/429#issuecomment-3117397673
> remove description control list
