IGNF/cartes.gouv.fr-entree-carto

src/components/menu/MenuLateralWrapper.vue
Le bouton "rouage" pour ouvrir le menu des widgets ne se positionne pas correctement sur petit écran : 
Le bouton est désormais positionné de manière absolue selon 3 média query (3 seuils).
A terme, il serait pertinent d'intégrer ce bouton à la grille des widgets.
Seuil supérieur à 627px de large
Seuil entre 576px et 627px de large
Seuil entre 382px et 576px de large
Seuil inférieur à  382px de large
=> fix(position:css): gestion en position absolue du bouton "menu widget"

public/data/edito.json, src/components.d.ts, src/components/carte/Controls.vue, src/components/carte/control/Share.vue, src/components/carte/control/Territories.vue, src/composables/controls.js, src/stores/dataStore.js
#26 (ticket chapeau)
#71 (ticket suivi)
> La liste des territoires est issue de l'edito (liste non exhaustive)
```json
[
{
"id": "FXX",
"title": "France métropolitaine",
"description": "",
"zoom": null,
"bbox": [
-9.86,
41.15,
10.38,
51.56
],
"thumbnail": "https://..."
}
]
```
Les ID suivent la nomenclature classique de l'IGN
ex. `GLP = guadeloupe`
**TODO** Liste des territoires à spécifier :
1. <gpp:Territory id="ANF" name="ANF">
2. <gpp:Territory id="ASP" name="ASP">
3. <gpp:Territory id="ATF" name="TERRES AUSTRALES ET ANTARCTIQUES FRANÇAISES">
4. <gpp:Territory id="CRZ" name="Crozet">
5. <gpp:Territory id="EUE" name="EUE">
6. <gpp:Territory id="FXX" name="FXX">
7. <gpp:Territory id="GLP" name="GLP">
8. <gpp:Territory id="GUF" name="GUF">
9. <gpp:Territory id="KER" name="Kerguelen">
10. …
=> Ajout du composant Territories

src/components/CartoAndTools.vue, src/components/carte/Controls.vue, src/components/carte/control/Share.vue, src/components/menu/MenuLateralWrapper.vue
- Le bouton partage se situe sous les widgets de mesure, ce qui risque de poser problème si d'autres se rajoutent
- Sur petit écran, les boutons catalogue, rouage, partage, positionnés en dur, ne s'adaptent pas et se superposent aux widgets
- Le bouton partage se situe directement sous le bouton catalogue, en fixe. Les widgets s'ajoutent et s'empilent après 
- Sur petit écran, les boutons catalogue, rouage, partage, sont repositionnés en dur au niveau de la barre de recherche
Les panels s'affichent en dehors de la carte et sont inutilisables.
Catalogue : 
Gestionnaire d'outils : 
Les panels s'affichent en plein écran et au dessus des autres éléments : 
Catalogue : …
=> Fix Recette : Réorganisation des boutons et des panels (menu, carto)

public/data/edito.json, src/components/carte/Controls.vue, src/stores/dataStore.js
Ajout des options sur le widget **SearchEngine**
```js
searchOptions: {
addToMap: false,
filterServices : "WMTS,WMS,TMS",
filterWMTSPriority : true,
filterLayersPriority : dataStore.getFeatured().toString(),
serviceOptions: {}
}
```
avec 
- `filterWMTSPriority` : https://github.com/IGNF/geopf-extensions-openlayers/issues/254
- `filterLayersPriority` permet de mettre en avant certaines couches sur la recherche, elles sont identifiées dans l'éditorial : 
```js
"featured" : [
"CADASTRALPARCELS.PARCELLAIRE_EXPRESS",
"GEOGRAPHICALGRIDSYSTEMS.PLANIGNV2",
"PLAN.IGN",
"LIMITES_ADMINISTRATIVES_EXPRESS.LATEST",
"ORTHOIMAGERY.ORTHOPHOTOS"
]
```
=> Ajout des options de filtres sur le widget SearchEngine

src/components/carte/Layer/Layer.vue, src/stores/dataStore.js
Permet d'afficher les couches /private de la clé "ign_scan_ws" : 
- on tape sur layers.json du projet
- on a ajouté au layers.json la config json de la clé "ign_scan_ws" (issue de https://geoplateforme-configuration.onrender.com/)
- on a ajouté à l'instanciation des couches de l'entrée carto (Layer.vue) la clé "ign_scan_ws"
Mais solution non viaible, par exemple, la couche club Vosgien continue de s'afficher en résultat de l'autocomplétion mais ne peut être ajoutée car non présente pour la clé "ign_scan_ws"
**Voir pour :** 
- ne pas taper sur le layers.json local
- utiliser une clé dédiée
- déterminer quelles couches private doivent être affichées
Les couches en …
=> fix(datastore): Gestion des couches privées dans la barre de recherche

package.json, src/main.ts
* Upgrade dsfr 1.11.2 --> 1.13.0
* Test de performance sur l'API Analytic avec le correctif : https://github.com/GouvernementFR/dsfr/issues/1048
Les performances sur l'execution des scripts de l'API Analytic  me semble correct : 
Pour information : 
> l'upgrade dsfr n'impacte pas **VueDsfr** qui utilise une autre version
```bash
$ npm ls @gouvfr/dsfr
cartes.gouv.fr-entree-carto@1.0.0 /home/JPBazonnais/Projets/PORTAIL/cartes.gouv.fr-entree-carto
├── @gouvfr/dsfr@1.13.0
├─┬ @gouvminint/vue-dsfr@5.22.0
│ └── @gouvfr/dsfr@1.11.2
└─┬ geopf-extensions-openlayers@1.0.0-beta.0-291
└── @gouvfr/dsfr@1.13.0 deduped
```
=> Upgrade dsfr 1.11.2 --> 1.13.0

src/components/carte/control/LayerSwitcher.vue, src/stores/mapStore.js
cf. issue #313 
Fix sur la synchronisation de l'ordre des couches avec le permalien lors d'un déplacement de couches dans le gestionnaire de couches
=> Fix sur la syncro de l'ordre des couches avec le permalien

src/composables/controls.js, src/composables/urlParams.js, src/stores/mapStore.js
On garde les widgets par défaut dans le permalien mais si on édite le permalien pour les retirer, ils sont quand même affichés
Les widgets par défaut ne sont pas bien gérés : on peut charger une interface sans eux si on édite un permalien
Les widgets par défaut sont toujours présents sur la carte.
Fix #400
=> fix(permalink): correction du #400, les widgets par defaut sont toujours ajoutés à la carte

DRAFT_CHANGELOG.md, package.json, src/components/carte/control/ContextMenu.vue
Mode mobile : le mneu contextuel est désactivé
https://github.com/IGNF/cartes.gouv.fr-entree-carto/issues/470
=> 🚑 mode mobile context menu

src/components/menu/MenuLateralWrapper.vue
fixes https://github.com/IGNF/cartes.gouv.fr-entree-carto/issues/471
il manquait une virgule !! :( :( :(
=> fix(menu): icones au dessus menu tierce (il manquait une virgule)

DRAFT_CHANGELOG.md, env/.env.stage, src/components.d.ts, src/components/carte/control/ShareModal.vue, src/components/utils/TextCopyToClipboard.vue
https://github.com/IGNF/cartes.gouv.fr-entree-carto/issues/479
100% front vérifier que la maquette ci dessous correspond. 
Attention
- interaction avec utilisateur après clic
- mode mobile
https://www.figma.com/design/Of9KQG60fBZPefncMuWL1j/Composants-suppl%C3%A9mentaires?node-id=2003-569&t=7g23PgjoYOMhWjlG-0
=> 💄 🌟 modif du bouton copier selon maquette UX

DRAFT_CHANGELOG.md, src/components/carte/control/Drawing.vue, src/components/carte/control/ElevationPath.vue, src/components/carte/control/Isocurve.vue, src/components/carte/control/Route.vue
Désactivation des boutons "Enregistrer" en attente de l'espace perso
Les boutons "Enregistrer" étaient présents sur l'entrée carto pour les widgets drawing, route, isocurve, altipath. Non fonctionnels tant qu'on a pas l'espace perso.
Les boutons enregistrer sont remplacés par les boutons "exporter" permettant d'exporter son croquis ou calcul. Ajout du menu pour choisir titre description et format
=> feat(compute/drawing): activation des boutons d'export

DRAFT_CHANGELOG.md, src/components/menu/catalogue/DataLayerCatalogue.vue, src/components/menu/catalogue/MenuCatalogue.vue, src/stores/dataStore.js
Le rendu des listes du catalogue sans condition v-if posait problème.
Cette nouvelle condition de rendu permet de ne générer la liste que si l'accordeon de la thématique ou du producteur est déroulée.
Par ailleurs il a fallu modifier le code d'enregistrement des thematiques et producteurs car en l'état on ajoutait parfois des catégories à ces listes alors qu'elles finissaient par s'avérer vide (exemple SCHAPI que des couches en WFS).
Or cela avait un impact sur le rendu du catalogue.
=> Vérifier que le chargement est court 
=> Vérifier que les catégories Autres sont bien remplies
=> Vérifier que la barre de recherche fonctionne toujours correctement.
=> opti perf de chargement catalogue

src/components/carte/Map.vue
cf. https://github.com/IGNF/cartes.gouv.fr-entree-carto/issues/525#issuecomment-2806979906
On évite de charger toutes les projections !
On charge uniquement celles par défaut : 
```js
/**
* Load definition projection by default
*
* include into proj4 :
* - WGS84
* - ['EPSG:4326']
* - ['EPSG:3785'], ['EPSG:3857'], GOOGLE, ['EPSG:900913'], ['EPSG:102113']
* +
* - ["EPSG:2154"], ["EPSG:27571"],  ["EPSG:27572"],  ["EPSG:27573"],  ["EPSG:2757"],
* - ["CRS:84"],
* - ["IGNF:LAMB93"],
* - ["IGNF:LAMBE"], ["IGNF:LAMB1"],  ["IGNF:LAMB2"],  ["IGNF:LAMB3"],  ["IGNF:LAMB4"],
* - ["IGNF:RGF93G"],
* - ["IGNF:WGS84G"]
*/
```
=> Eviter le chargement de toutes les projections

src/components/CartoAndTools.vue
voir https://github.com/IGNF/cartes.gouv.fr-entree-carto/issues/457#issuecomment-2809897449
Solution pas parfaite du tout (le widget spécifique entree carto se réouvre après), mais a l'avantage de ne pas nécessiter ajouter des évènements dans tous les sens sur les widgets des extensions...
=> fix: 1 seul bouton ouvert quand widget cliqué après menu spécifique entree carto

DRAFT_CHANGELOG.md, src/components/CartoAndTools.vue, src/components/menu/MenuLateralWrapper.vue
Correction de ce comportement : https://github.com/IGNF/cartes.gouv.fr-entree-carto/issues/560
Même solution que dans cette PR : https://github.com/IGNF/cartes.gouv.fr-entree-carto/pull/535
Solution :
On cache le menu tant qu'une fenêtre d'annotation est ouverte
=> 🚑 fenêtre de croquis cachée par le panel entrée carto

src/components/carte/Map.vue
Retrait du spinner au chargement de dalles (loadstart, loadend)
Numéro du ticket : fix #526
Plus de spinner sur la map
Focus sur input "Enregistrer" reste stable
=> fix(map): retrait du spinner openlayers sur la map

DRAFT_CHANGELOG.md, src/components/carte/control/ShareModal.vue
Retrait du bouton copier coller inutile du composant share
Bouton de partage inutie et non fonctionnel (celui après les RS) : 
Numéro du ticket : fix #589
Bouton caché en CSS (car le composant VueDSFR semble en imposer un)
=> fix(ui:share): boutton copy-paste retiré car inutile (fix #589)

public/data/alerts.json, src/components.d.ts, src/components/modals/ModalConsent.vue, src/components/modals/ModalConsentCustom.vue, src/views/Main.vue
Si pas de clef de storage, on affiche la boite de dialogue de consentement standard :
On peut personnaliser les cookies (même si on n'en a pas !?) du site en cliquant sur : 
* le bouton "personnaliser" de la boite de consentement standard
* le lien "gestion des cookies"
Pour recetter, 
> supprimer la clef du localStorage pour faire apparaître la modale de consentement standard.
=> Ajout d'une fenêtre consentement standard et personnalisé

.docker-dev/carto/Dockerfile, env/.env.docker-local, package.json, src/services/ServiceBase.js, src/services/ServiceUsers.js, src/views/Main.vue
**Hack** uniquement valable sur un même navigateur (donc même session) !
- Si on est connecté sur "cartes.gouv.fr", le passage à l'entrée carto doit mettre à jour l'authentification : _le nom apparaît_.
- Si on est déconnecté sur "cartes.gouv.fr", le passage à l'entrée carto doit mettre à jour l'authentification : _le nom n'apparaît pas_.
Comment recetter ?
``` bash
$ docker compose -f .docker-dev/docker-compose.yml watch
[+] Running 4/4
✔ entree_carto_dev                               Built
✔ Container cartesgouvfr-dev               Running 
✔ Container cartesgouvfr-nginx_proxy-dev   Started
✔ Container cartesgouvfr-entree_carto-dev  Started 
```
Puis, ouvrir le navigateur **Firefox** sur l'url suivante : http://localhost:1235
**Note:**
> Ceci est un hack !
> Pour une gestion des auth, …
=> Synchronisation de l'authentification avec cartes.gouv.fr

DRAFT_CHANGELOG.md, env/.env.docker-local, src/components/carte/control/LayerSwitcher.vue, src/stores/dataStore.js
Les **globalConstraints** fournies par le service de configuration précisent l'emprise de la donnée : 
```js
globalConstraint: {
crs: "EPSG:3857",
bbox: {
left: 222569.48368345576,
right: 653827.9949274634,
top: 6491207.83699174,
bottom: 6097028.181821302
},
minScaleDenominator: 279541132.01435894,
maxScaleDenominator: 2132.7295838497826
}
```
On utilise la projection de la **globalConstraint** pour réaliser une reprojection (si nécessaire) dans le système de la carte.
Si la projection n'est pas renseignée dans la **globalConstraint**, on estime que l'emprise est en géographique (EPSG:4326).
=> Fix sur les emprises sur le zoomToExtent pour les TMS

DRAFT_CHANGELOG.md, src/components/carte/Controls.vue, src/components/carte/control/ControlList.vue, src/composables/controls.js
fixes https://github.com/IGNF/cartes.gouv.fr-entree-carto/issues/638
\+ une partie de https://github.com/IGNF/cartes.gouv.fr-entree-carto/issues/650
> Lorsqu'un seul outil d'activé, afficher celui-ci systématiquement et jamais le widget additionnel
=> ui(controllist): ne change plus d'emplacement en fonction de la taille de l'écran

DRAFT_CHANGELOG.md, src/composables/urlParams.js
Charger une carte enregistrée. Les widgets permanents ayant été retirés des permaliens (#625), ils ne sont pas chargées : l'interface ne propose plus le layerSwitcher et les autres widgets permanents au chargement d'une carte enregistrée.
Numéro du ticket : #698
Au chargement d'un permalien, on ajoute les widgets par défaut à la liste du paramètres widgets. Les widgets par défaut sont ainsi bien chargés.
=> fix(espace-perso): chargement cartes enregistrée, cf #698

DRAFT_CHANGELOG.md, src/components/carte/control/Legends.vue, src/components/carte/control/Territories.vue
Les panels des widgets situés en bas à gauche (teritories + legendes) s'alignent verticalement avec les panels en haut à gauche.
*Je suis preneur si vous avez une solution plus propre pour se passer du !important :-1:**
Lié aux évols du #704 #705
=> fix(position:widgets): alignement top-left des panels des widgets botom-left
